### ISSUE TITLE
digikam stopped working with update to 7.1.0 

### ISSUE THREAD

**Issue by linuxrider** [flathub/org.kde.digikam#13] opened 2020-09-18 15:43 UTC
digikam stopped working with update to 7.1.0  with the following message:

`ASSERT failure in KCatalogPrivate::setupGettextEnv: "You need to instantiate a Q*Application before using KCatalog", file src/kcatalog.cpp, line 223`

**Comment by Erick555** [comment] 2020-09-18 16:45
Works for me

**Comment by tsdgeos** [comment] 2020-09-18 17:58
I can reproduce the problem. I'll have a look

**Comment by tsdgeos** [comment] 2020-09-19 16:14
Fixed by #15  Will be ready as an update in a few hours

**Closed by tsdgeos** 2020-09-19 16:14 UTC
