### ISSUE TITLE
Digikam 7.8.0 fails to run on Raspberry PI arm64

### ISSUE THREAD

**Issue by sfatula** [flathub/org.kde.digikam#47] opened 2022-10-08 18:54 UTC
digikam.metaengine: Cannot load metadata from file with Exiv2 backend: /home/sfatula/Pictures/Processed/Vacations/Kauai/20210902T182127.HEIC  (Error # 11 :  "/home/sfatula/Pictures/Processed/Vacations/Kauai/20210902T182127.HEIC: The file contains data of an unknown image type"
digikam: /run/build/heif/libheif/box.cc:1114: heif::Error heif::Box_iloc::read_data(const heif::Box_iloc::Item&, std::shared_ptr<heif::StreamReader>, const std::shared_ptr<heif::Box_idat>&, std::vector<unsigned char>*) const: Assertion `success' failed.

Since many mobile phone images are of this format, this is a major problem.

**Comment by ElXreno** [comment] 2022-10-13 13:00
Hi! Thanks for your report!
Could you please check this build to see if the problem is fixed for you? https://github.com/flathub/org.kde.digikam/pull/41#issuecomment-1277569947

**Comment by sfatula** [comment] 2022-10-13 17:47
It does indeed appear to work. Will use it for an album and report back if it does not work. Thanks! The Flatpak is more complete than the snap, which also does not work. And the appimage doesn't work as it's not for arm64. That left me with the flatpak, whichj wasn't running or building my own which i did actually but would rather use the flatpak.

**Comment by sfatula** [comment] 2022-10-28 04:18
It has worked for everything I can throw at it, thanks a bunch! Hopefully can install an official version at some point.

**Comment by ElXreno** [comment] 2022-10-30 23:49
Thanks for the report! Now I'm closing this issue. Feel free to reopen this issue if you face the same problem.

**Closed by ElXreno** 2022-10-30 23:49 UTC
